//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
// Created via this command line: "C:\Users\vblinkov\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"http://isupp/RTPROJECTS" /namespace:"Xdsoft.RTK.CRMData.Entities" /out:"C:\Users\vblinkov\AppData\Roaming\MscrmTools\XrmToolBox\Settings\CrmSvcUtil Ref\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"Vblinkov" /password:"********" /domain:"DOR" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Xdsoft.RTK.CRMData.Entities
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.ActivityMimeAttachment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.ActivityMimeAttachment> ActivityMimeAttachmentSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.ActivityMimeAttachment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.Annotation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.Annotation> AnnotationSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.Annotation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.BusinessUnit"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.BusinessUnit> BusinessUnitSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.BusinessUnit>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.Email"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.Email> EmailSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.Email>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_contract_plan"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_contract_plan> new_contract_planSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_contract_plan>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_contract_plan_acception"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_contract_plan_acception> new_contract_plan_acceptionSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_contract_plan_acception>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_contract_plan_adjustment_cc"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_contract_plan_adjustment_cc> new_contract_plan_adjustment_ccSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_contract_plan_adjustment_cc>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_contract_plan_product"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_contract_plan_product> new_contract_plan_productSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_contract_plan_product>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_d_product_catalog"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_d_product_catalog> new_d_product_catalogSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_d_product_catalog>();
			}
		}
		
	
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_project_initiative_valuation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_project_initiative_valuation> new_project_initiative_valuationSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_project_initiative_valuation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_Route"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_Route> new_RouteSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_Route>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_setting"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_setting> new_settingSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_setting>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_Step"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_Step> new_StepSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_Step>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_t_activity"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_t_activity> new_t_activitySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_t_activity>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_territory"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_territory> new_territorySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_territory>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.new_Transfer"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.new_Transfer> new_TransferSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.new_Transfer>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Xdsoft.RTK.CRMData.Entities.Workflow"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Xdsoft.RTK.CRMData.Entities.Workflow> WorkflowSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Xdsoft.RTK.CRMData.Entities.Workflow>();
			}
		}
	}
	
	internal sealed class EntityOptionSetEnum
	{
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
}