//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum new_project_initiative_valuationState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_project_initiative_valuation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public partial class new_project_initiative_valuation : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string new_AgreederComment = "new_agreedercomment";
			public const string new_ApproverComment = "new_approvercomment";
			public const string new_essential_factors_description = "new_essential_factors_description";
			public const string new_IsAgreed = "new_isagreed";
			public const string new_IsApproved = "new_isapproved";
			public const string new_KeyTask_TaskId = "new_keytask_taskid";
			public const string new_link_account_id = "new_link_account_id";
			public const string new_link_deal_type_id = "new_link_deal_type_id";
			public const string new_link_decision_making_level_id = "new_link_decision_making_level_id";
			public const string new_link_project_initiative_id = "new_link_project_initiative_id";
			public const string new_name = "new_name";
			public const string new_parameter_project_initiativeId = "new_parameter_project_initiativeid";
			public const string new_prjct_initv_valuation_agreeder = "new_prjct_initv_valuation_agreeder";
			public const string new_prjct_initv_valuation_approver = "new_prjct_initv_valuation_approver";
			public const string new_project_initiative_valuationId = "new_project_initiative_valuationid";
			public const string Id = "new_project_initiative_valuationid";
			public const string new_project_type_id = "new_project_type_id";
			public const string new_RouteId = "new_routeid";
			public const string new_StageId = "new_stageid";
			public const string new_StepDateStart = "new_stepdatestart";
			public const string new_StepId = "new_stepid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string new_new_route_new_project_initiative_valuatio = "new_new_route_new_project_initiative_valuatio";
			public const string new_new_step_new_project_initiative_valuation = "new_new_step_new_project_initiative_valuation";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public new_project_initiative_valuation() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "new_project_initiative_valuation";
		
		public const string PrimaryIdAttribute = "new_project_initiative_valuationid";
		
		public const string PrimaryNameAttribute = "new_name";
		
		public const int EntityTypeCode = 10088;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя, создавшего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Дата и время создания записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя-делегата, создавшего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Порядковый номер импорта, в результате которого была создана эта запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя, изменившего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Дата и время изменения записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя-делегата, изменившего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_agreedercomment")]
		public string new_AgreederComment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("new_agreedercomment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_AgreederComment");
				this.SetAttributeValue("new_agreedercomment", value);
				this.OnPropertyChanged("new_AgreederComment");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_approvercomment")]
		public string new_ApproverComment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("new_approvercomment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_ApproverComment");
				this.SetAttributeValue("new_approvercomment", value);
				this.OnPropertyChanged("new_ApproverComment");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_essential_factors_description")]
		public string new_essential_factors_description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("new_essential_factors_description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_essential_factors_description");
				this.SetAttributeValue("new_essential_factors_description", value);
				this.OnPropertyChanged("new_essential_factors_description");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_isagreed")]
		public System.Nullable<bool> new_IsAgreed
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_isagreed");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_IsAgreed");
				this.SetAttributeValue("new_isagreed", value);
				this.OnPropertyChanged("new_IsAgreed");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_isapproved")]
		public System.Nullable<bool> new_IsApproved
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_isapproved");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_IsApproved");
				this.SetAttributeValue("new_isapproved", value);
				this.OnPropertyChanged("new_IsApproved");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Поручение, связанного с объектом Оценка проектной инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_keytask_taskid")]
		public Microsoft.Xrm.Sdk.EntityReference new_KeyTask_TaskId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_keytask_taskid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_KeyTask_TaskId");
				this.SetAttributeValue("new_keytask_taskid", value);
				this.OnPropertyChanged("new_KeyTask_TaskId");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Контрагент, связанного с объектом Оценка инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_account_id")]
		public Microsoft.Xrm.Sdk.EntityReference new_link_account_id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_link_account_id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_link_account_id");
				this.SetAttributeValue("new_link_account_id", value);
				this.OnPropertyChanged("new_link_account_id");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Тип сделки, связанного с объектом Оценка инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_deal_type_id")]
		public Microsoft.Xrm.Sdk.EntityReference new_link_deal_type_id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_link_deal_type_id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_link_deal_type_id");
				this.SetAttributeValue("new_link_deal_type_id", value);
				this.OnPropertyChanged("new_link_deal_type_id");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Уровень принятия решения, связанного с объектом Оценка инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_decision_making_level_id")]
		public Microsoft.Xrm.Sdk.EntityReference new_link_decision_making_level_id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_link_decision_making_level_id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_link_decision_making_level_id");
				this.SetAttributeValue("new_link_decision_making_level_id", value);
				this.OnPropertyChanged("new_link_decision_making_level_id");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Проектная инициатива, связанного с объектом Оценка проектной инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_project_initiative_id")]
		public Microsoft.Xrm.Sdk.EntityReference new_link_project_initiative_id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_link_project_initiative_id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_link_project_initiative_id");
				this.SetAttributeValue("new_link_project_initiative_id", value);
				this.OnPropertyChanged("new_link_project_initiative_id");
			}
		}
		
		/// <summary>
		/// Имя настраиваемой сущности.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name")]
		public string new_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("new_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_name");
				this.SetAttributeValue("new_name", value);
				this.OnPropertyChanged("new_name");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Параметр оценки проектной инициативы, связанного с объектом Оценка проектной инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_parameter_project_initiativeid")]
		public Microsoft.Xrm.Sdk.EntityReference new_parameter_project_initiativeId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_parameter_project_initiativeid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_parameter_project_initiativeId");
				this.SetAttributeValue("new_parameter_project_initiativeid", value);
				this.OnPropertyChanged("new_parameter_project_initiativeId");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Пользователь, связанного с объектом Оценка проектной инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_prjct_initv_valuation_agreeder")]
		public Microsoft.Xrm.Sdk.EntityReference new_prjct_initv_valuation_agreeder
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_prjct_initv_valuation_agreeder");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_prjct_initv_valuation_agreeder");
				this.SetAttributeValue("new_prjct_initv_valuation_agreeder", value);
				this.OnPropertyChanged("new_prjct_initv_valuation_agreeder");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Пользователь, связанного с объектом Оценка проектной инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_prjct_initv_valuation_approver")]
		public Microsoft.Xrm.Sdk.EntityReference new_prjct_initv_valuation_approver
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_prjct_initv_valuation_approver");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_prjct_initv_valuation_approver");
				this.SetAttributeValue("new_prjct_initv_valuation_approver", value);
				this.OnPropertyChanged("new_prjct_initv_valuation_approver");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор экземпляров сущности
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_project_initiative_valuationid")]
		public System.Nullable<System.Guid> new_project_initiative_valuationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("new_project_initiative_valuationid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_project_initiative_valuationId");
				this.SetAttributeValue("new_project_initiative_valuationid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("new_project_initiative_valuationId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_project_initiative_valuationid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.new_project_initiative_valuationId = value;
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Тип проекта, связанного с объектом Оценка инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_project_type_id")]
		public Microsoft.Xrm.Sdk.EntityReference new_project_type_id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_project_type_id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_project_type_id");
				this.SetAttributeValue("new_project_type_id", value);
				this.OnPropertyChanged("new_project_type_id");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Маршрут, связанного с объектом Оценка проектной инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_routeid")]
		public Microsoft.Xrm.Sdk.EntityReference new_RouteId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_routeid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_RouteId");
				this.SetAttributeValue("new_routeid", value);
				this.OnPropertyChanged("new_RouteId");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Этап, связанного с объектом Оценка проектной инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_stageid")]
		public Microsoft.Xrm.Sdk.EntityReference new_StageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_stageid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_StageId");
				this.SetAttributeValue("new_stageid", value);
				this.OnPropertyChanged("new_StageId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_stepdatestart")]
		public System.Nullable<System.DateTime> new_StepDateStart
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_stepdatestart");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_StepDateStart");
				this.SetAttributeValue("new_stepdatestart", value);
				this.OnPropertyChanged("new_StepDateStart");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Шаг, связанного с объектом Оценка проектной инициативы.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_stepid")]
		public Microsoft.Xrm.Sdk.EntityReference new_StepId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_stepid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_StepId");
				this.SetAttributeValue("new_stepid", value);
				this.OnPropertyChanged("new_StepId");
			}
		}
		
		/// <summary>
		/// Дата и время переноса записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Идентификатор ответственного
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор подразделения, владеющего этой записью
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор группы, владеющей записью
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя, владеющего этой записью.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Статус Оценка инициативы
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Xdsoft.RTK.CRMData.Entities.new_project_initiative_valuationState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Xdsoft.RTK.CRMData.Entities.new_project_initiative_valuationState)(System.Enum.ToObject(typeof(Xdsoft.RTK.CRMData.Entities.new_project_initiative_valuationState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Причина состояния Оценка инициативы
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Только для внутреннего использования.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Код часового пояса, использовавшийся при создании записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Номер версии
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N new_project_initiative_valuation_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_project_initiative_valuation_Annotations")]
		public System.Collections.Generic.IEnumerable<Xdsoft.RTK.CRMData.Entities.Annotation> new_project_initiative_valuation_Annotations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Xdsoft.RTK.CRMData.Entities.Annotation>("new_project_initiative_valuation_Annotations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_project_initiative_valuation_Annotations");
				this.SetRelatedEntities<Xdsoft.RTK.CRMData.Entities.Annotation>("new_project_initiative_valuation_Annotations", null, value);
				this.OnPropertyChanged("new_project_initiative_valuation_Annotations");
			}
		}
		
		/// <summary>
		/// N:1 new_new_route_new_project_initiative_valuatio
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_routeid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_route_new_project_initiative_valuatio")]
		public Xdsoft.RTK.CRMData.Entities.new_Route new_new_route_new_project_initiative_valuatio
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Xdsoft.RTK.CRMData.Entities.new_Route>("new_new_route_new_project_initiative_valuatio", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_new_route_new_project_initiative_valuatio");
				this.SetRelatedEntity<Xdsoft.RTK.CRMData.Entities.new_Route>("new_new_route_new_project_initiative_valuatio", null, value);
				this.OnPropertyChanged("new_new_route_new_project_initiative_valuatio");
			}
		}
		
		/// <summary>
		/// N:1 new_new_step_new_project_initiative_valuation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_stepid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_step_new_project_initiative_valuation")]
		public Xdsoft.RTK.CRMData.Entities.new_Step new_new_step_new_project_initiative_valuation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Xdsoft.RTK.CRMData.Entities.new_Step>("new_new_step_new_project_initiative_valuation", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_new_step_new_project_initiative_valuation");
				this.SetRelatedEntity<Xdsoft.RTK.CRMData.Entities.new_Step>("new_new_step_new_project_initiative_valuation", null, value);
				this.OnPropertyChanged("new_new_step_new_project_initiative_valuation");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public new_project_initiative_valuation(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["new_project_initiative_valuationid"] = base.Id;
                        break;
                    case "new_project_initiative_valuationid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual new_project_initiative_valuation_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((new_project_initiative_valuation_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}