//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum new_contract_planState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_contract_plan")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public partial class new_contract_plan : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string new_1_auarter = "new_1_auarter";
			public const string new_1_auarter_Date = "new_1_auarter_date";
			public const string new_1_auarter_State = "new_1_auarter_state";
			public const string new_acception_result = "new_acception_result";
			public const string new_contract_plan_acception_id = "new_contract_plan_acception_id";
			public const string new_contract_planId = "new_contract_planid";
			public const string Id = "new_contract_planid";
			public const string new_link_businessunit_id = "new_link_businessunit_id";
			public const string new_link_businessunit_MRF_id = "new_link_businessunit_mrf_id";
			public const string new_link_product_group_id = "new_link_product_group_id";
			public const string new_link_product_id = "new_link_product_id";
			public const string new_link_territory_id = "new_link_territory_id";
			public const string new_product_sum = "new_product_sum";
			public const string new_quarter = "new_quarter";
			public const string new_service_type = "new_service_type";
			public const string new_year = "new_year";
			public const string new_year_number = "new_year_number";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string business_unit_new_contract_plan = "business_unit_new_contract_plan";
			public const string new_businessunit_MRF_new_contract_plan = "new_businessunit_MRF_new_contract_plan";
			public const string new_businessunit_new_contract_plan = "new_businessunit_new_contract_plan";
			public const string new_new_contract_plan_acception_new_contract_ = "new_new_contract_plan_acception_new_contract_";
			public const string new_new_d_product_catalog_new_contract_plan = "new_new_d_product_catalog_new_contract_plan";
			public const string new_new_territory_new_contract_plan = "new_new_territory_new_contract_plan";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public new_contract_plan() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "new_contract_plan";
		
		public const string PrimaryIdAttribute = "new_contract_planid";
		
		public const string PrimaryNameAttribute = "new_year";
		
		public const int EntityTypeCode = 10084;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя, создавшего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Дата и время создания записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя-делегата, создавшего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Порядковый номер импорта, в результате которого была создана эта запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя, изменившего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Дата и время изменения записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя-делегата, изменившего запись.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_1_auarter")]
		public System.Nullable<decimal> new_1_auarter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("new_1_auarter");
			}
		}
		
		/// <summary>
		/// Время последнего обновления поля свертки Свертка кв1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_1_auarter_date")]
		public System.Nullable<System.DateTime> new_1_auarter_Date
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_1_auarter_date");
			}
		}
		
		/// <summary>
		/// Состояние поля свертки Свертка кв1.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_1_auarter_state")]
		public System.Nullable<int> new_1_auarter_State
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_1_auarter_state");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_acception_result")]
		public Microsoft.Xrm.Sdk.OptionSetValue new_acception_result
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("new_acception_result");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_acception_result");
				this.SetAttributeValue("new_acception_result", value);
				this.OnPropertyChanged("new_acception_result");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Утверждение плана контрактования, связанного с объектом План контрактования (год).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contract_plan_acception_id")]
		public Microsoft.Xrm.Sdk.EntityReference new_contract_plan_acception_id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_contract_plan_acception_id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_contract_plan_acception_id");
				this.SetAttributeValue("new_contract_plan_acception_id", value);
				this.OnPropertyChanged("new_contract_plan_acception_id");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор экземпляров сущности
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contract_planid")]
		public System.Nullable<System.Guid> new_contract_planId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("new_contract_planid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_contract_planId");
				this.SetAttributeValue("new_contract_planid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("new_contract_planId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contract_planid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.new_contract_planId = value;
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Подразделение, связанного с объектом План контрактования.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_businessunit_id")]
		public Microsoft.Xrm.Sdk.EntityReference new_link_businessunit_id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_link_businessunit_id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_link_businessunit_id");
				this.SetAttributeValue("new_link_businessunit_id", value);
				this.OnPropertyChanged("new_link_businessunit_id");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Подразделение, связанного с объектом План контрактования (год).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_businessunit_mrf_id")]
		public Microsoft.Xrm.Sdk.EntityReference new_link_businessunit_MRF_id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_link_businessunit_mrf_id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_link_businessunit_MRF_id");
				this.SetAttributeValue("new_link_businessunit_mrf_id", value);
				this.OnPropertyChanged("new_link_businessunit_MRF_id");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Продуктовая группа, связанного с объектом План контрактования.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_product_group_id")]
		public Microsoft.Xrm.Sdk.EntityReference new_link_product_group_id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_link_product_group_id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_link_product_group_id");
				this.SetAttributeValue("new_link_product_group_id", value);
				this.OnPropertyChanged("new_link_product_group_id");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Продукт, связанного с объектом План контрактования.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_product_id")]
		public Microsoft.Xrm.Sdk.EntityReference new_link_product_id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_link_product_id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_link_product_id");
				this.SetAttributeValue("new_link_product_id", value);
				this.OnPropertyChanged("new_link_product_id");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор для объекта Субъект РФ, связанного с объектом План контрактования.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_territory_id")]
		public Microsoft.Xrm.Sdk.EntityReference new_link_territory_id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_link_territory_id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_link_territory_id");
				this.SetAttributeValue("new_link_territory_id", value);
				this.OnPropertyChanged("new_link_territory_id");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_product_sum")]
		public System.Nullable<decimal> new_product_sum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("new_product_sum");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_product_sum");
				this.SetAttributeValue("new_product_sum", value);
				this.OnPropertyChanged("new_product_sum");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quarter")]
		public Microsoft.Xrm.Sdk.OptionSetValue new_quarter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("new_quarter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_quarter");
				this.SetAttributeValue("new_quarter", value);
				this.OnPropertyChanged("new_quarter");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_service_type")]
		public Microsoft.Xrm.Sdk.OptionSetValue new_service_type
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("new_service_type");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_service_type");
				this.SetAttributeValue("new_service_type", value);
				this.OnPropertyChanged("new_service_type");
			}
		}
		
		/// <summary>
		/// Имя настраиваемой сущности.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_year")]
		public string new_year
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("new_year");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_year");
				this.SetAttributeValue("new_year", value);
				this.OnPropertyChanged("new_year");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_year_number")]
		public System.Nullable<int> new_year_number
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_year_number");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_year_number");
				this.SetAttributeValue("new_year_number", value);
				this.OnPropertyChanged("new_year_number");
			}
		}
		
		/// <summary>
		/// Дата и время переноса записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Идентификатор ответственного
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор подразделения, владеющего этой записью
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор группы, владеющей записью
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Уникальный идентификатор пользователя, владеющего этой записью.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Статус План контрактования
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Xdsoft.RTK.CRMData.Entities.new_contract_planState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Xdsoft.RTK.CRMData.Entities.new_contract_planState)(System.Enum.ToObject(typeof(Xdsoft.RTK.CRMData.Entities.new_contract_planState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Причина состояния План контрактования
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Только для внутреннего использования.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Код часового пояса, использовавшийся при создании записи.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Номер версии
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N new_contract_plan_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_contract_plan_Annotations")]
		public System.Collections.Generic.IEnumerable<Xdsoft.RTK.CRMData.Entities.Annotation> new_contract_plan_Annotations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Xdsoft.RTK.CRMData.Entities.Annotation>("new_contract_plan_Annotations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_contract_plan_Annotations");
				this.SetRelatedEntities<Xdsoft.RTK.CRMData.Entities.Annotation>("new_contract_plan_Annotations", null, value);
				this.OnPropertyChanged("new_contract_plan_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N new_contract_plan_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_contract_plan_Emails")]
		public System.Collections.Generic.IEnumerable<Xdsoft.RTK.CRMData.Entities.Email> new_contract_plan_Emails
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Xdsoft.RTK.CRMData.Entities.Email>("new_contract_plan_Emails", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_contract_plan_Emails");
				this.SetRelatedEntities<Xdsoft.RTK.CRMData.Entities.Email>("new_contract_plan_Emails", null, value);
				this.OnPropertyChanged("new_contract_plan_Emails");
			}
		}
		
		/// <summary>
		/// 1:N new_new_contract_plan_new_contract_plan_produ
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_contract_plan_new_contract_plan_produ")]
		public System.Collections.Generic.IEnumerable<Xdsoft.RTK.CRMData.Entities.new_contract_plan_product> new_new_contract_plan_new_contract_plan_produ
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Xdsoft.RTK.CRMData.Entities.new_contract_plan_product>("new_new_contract_plan_new_contract_plan_produ", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_new_contract_plan_new_contract_plan_produ");
				this.SetRelatedEntities<Xdsoft.RTK.CRMData.Entities.new_contract_plan_product>("new_new_contract_plan_new_contract_plan_produ", null, value);
				this.OnPropertyChanged("new_new_contract_plan_new_contract_plan_produ");
			}
		}
		
	
		/// <summary>
		/// N:1 business_unit_new_contract_plan
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_new_contract_plan")]
		public Xdsoft.RTK.CRMData.Entities.BusinessUnit business_unit_new_contract_plan
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Xdsoft.RTK.CRMData.Entities.BusinessUnit>("business_unit_new_contract_plan", null);
			}
		}
		
		/// <summary>
		/// N:1 new_businessunit_MRF_new_contract_plan
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_businessunit_mrf_id")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_businessunit_MRF_new_contract_plan")]
		public Xdsoft.RTK.CRMData.Entities.BusinessUnit new_businessunit_MRF_new_contract_plan
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Xdsoft.RTK.CRMData.Entities.BusinessUnit>("new_businessunit_MRF_new_contract_plan", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_businessunit_MRF_new_contract_plan");
				this.SetRelatedEntity<Xdsoft.RTK.CRMData.Entities.BusinessUnit>("new_businessunit_MRF_new_contract_plan", null, value);
				this.OnPropertyChanged("new_businessunit_MRF_new_contract_plan");
			}
		}
		
		/// <summary>
		/// N:1 new_businessunit_new_contract_plan
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_businessunit_id")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_businessunit_new_contract_plan")]
		public Xdsoft.RTK.CRMData.Entities.BusinessUnit new_businessunit_new_contract_plan
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Xdsoft.RTK.CRMData.Entities.BusinessUnit>("new_businessunit_new_contract_plan", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_businessunit_new_contract_plan");
				this.SetRelatedEntity<Xdsoft.RTK.CRMData.Entities.BusinessUnit>("new_businessunit_new_contract_plan", null, value);
				this.OnPropertyChanged("new_businessunit_new_contract_plan");
			}
		}
		
		/// <summary>
		/// N:1 new_new_contract_plan_acception_new_contract_
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contract_plan_acception_id")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_contract_plan_acception_new_contract_")]
		public Xdsoft.RTK.CRMData.Entities.new_contract_plan_acception new_new_contract_plan_acception_new_contract_
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Xdsoft.RTK.CRMData.Entities.new_contract_plan_acception>("new_new_contract_plan_acception_new_contract_", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_new_contract_plan_acception_new_contract_");
				this.SetRelatedEntity<Xdsoft.RTK.CRMData.Entities.new_contract_plan_acception>("new_new_contract_plan_acception_new_contract_", null, value);
				this.OnPropertyChanged("new_new_contract_plan_acception_new_contract_");
			}
		}
		
		/// <summary>
		/// N:1 new_new_d_product_catalog_new_contract_plan
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_product_id")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_d_product_catalog_new_contract_plan")]
		public Xdsoft.RTK.CRMData.Entities.new_d_product_catalog new_new_d_product_catalog_new_contract_plan
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Xdsoft.RTK.CRMData.Entities.new_d_product_catalog>("new_new_d_product_catalog_new_contract_plan", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_new_d_product_catalog_new_contract_plan");
				this.SetRelatedEntity<Xdsoft.RTK.CRMData.Entities.new_d_product_catalog>("new_new_d_product_catalog_new_contract_plan", null, value);
				this.OnPropertyChanged("new_new_d_product_catalog_new_contract_plan");
			}
		}
		
		/// <summary>
		/// N:1 new_new_territory_new_contract_plan
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_link_territory_id")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_territory_new_contract_plan")]
		public Xdsoft.RTK.CRMData.Entities.new_territory new_new_territory_new_contract_plan
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Xdsoft.RTK.CRMData.Entities.new_territory>("new_new_territory_new_contract_plan", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("new_new_territory_new_contract_plan");
				this.SetRelatedEntity<Xdsoft.RTK.CRMData.Entities.new_territory>("new_new_territory_new_contract_plan", null, value);
				this.OnPropertyChanged("new_new_territory_new_contract_plan");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public new_contract_plan(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["new_contract_planid"] = base.Id;
                        break;
                    case "new_contract_planid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_acception_result")]
		public virtual new_negotiationoptionslist? new_acception_resultEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((new_negotiationoptionslist?)(EntityOptionSetEnum.GetEnum(this, "new_acception_result")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				new_acception_result = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quarter")]
		public virtual new_quarter? new_quarterEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((new_quarter?)(EntityOptionSetEnum.GetEnum(this, "new_quarter")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				new_quarter = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_service_type")]
		public virtual new_service_type? new_service_typeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((new_service_type?)(EntityOptionSetEnum.GetEnum(this, "new_service_type")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				new_service_type = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual new_contract_plan_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((new_contract_plan_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}