//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.ExtCrmWeb
{
    
    
    /// <summary>
    /// The TutorialSection Configuration Section.
    /// </summary>
    public partial class TutorialSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the TutorialSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string TutorialSectionSectionName = "tutorialSection";
        
        /// <summary>
        /// The XML path of the TutorialSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string TutorialSectionSectionPath = "tutorialSection";
        
        /// <summary>
        /// Gets the TutorialSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public static global::Xdsoft.RTK.ExtCrmWeb.TutorialSection Instance
        {
            get
            {
                return ((global::Xdsoft.RTK.ExtCrmWeb.TutorialSection)(global::System.Configuration.ConfigurationManager.GetSection(global::Xdsoft.RTK.ExtCrmWeb.TutorialSection.TutorialSectionSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Xdsoft.RTK.ExtCrmWeb.TutorialSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Xdsoft.RTK.ExtCrmWeb.TutorialSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Foobars Property
        /// <summary>
        /// The XML name of the <see cref="Foobars"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string FoobarsPropertyName = "foobars";
        
        /// <summary>
        /// Gets or sets the Foobars.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Foobars.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Xdsoft.RTK.ExtCrmWeb.TutorialSection.FoobarsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Xdsoft.RTK.ExtCrmWeb.Foobar Foobars
        {
            get
            {
                return ((global::Xdsoft.RTK.ExtCrmWeb.Foobar)(base[global::Xdsoft.RTK.ExtCrmWeb.TutorialSection.FoobarsPropertyName]));
            }
            set
            {
                base[global::Xdsoft.RTK.ExtCrmWeb.TutorialSection.FoobarsPropertyName] = value;
            }
        }
        #endregion
        
        #region Tutorial Property
        /// <summary>
        /// The XML name of the <see cref="Tutorial"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string TutorialPropertyName = "tutorial";
        
        /// <summary>
        /// Gets or sets the Tutorial.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Tutorial.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Xdsoft.RTK.ExtCrmWeb.TutorialSection.TutorialPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Xdsoft.RTK.ExtCrmWeb.Tutorial Tutorial
        {
            get
            {
                return ((global::Xdsoft.RTK.ExtCrmWeb.Tutorial)(base[global::Xdsoft.RTK.ExtCrmWeb.TutorialSection.TutorialPropertyName]));
            }
            set
            {
                base[global::Xdsoft.RTK.ExtCrmWeb.TutorialSection.TutorialPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Xdsoft.RTK.ExtCrmWeb
{
    
    
    /// <summary>
    /// The Tutorial Configuration Element.
    /// </summary>
    public partial class Tutorial : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace Xdsoft.RTK.ExtCrmWeb
{
    
    
    /// <summary>
    /// The Foobar Configuration Element.
    /// </summary>
    public partial class Foobar : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Key Property
        /// <summary>
        /// The XML name of the <see cref="Key"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string KeyPropertyName = "key";
        
        /// <summary>
        /// Gets or sets the Key.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Key.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Xdsoft.RTK.ExtCrmWeb.Foobar.KeyPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Key
        {
            get
            {
                return ((string)(base[global::Xdsoft.RTK.ExtCrmWeb.Foobar.KeyPropertyName]));
            }
            set
            {
                base[global::Xdsoft.RTK.ExtCrmWeb.Foobar.KeyPropertyName] = value;
            }
        }
        #endregion
    }
}
