//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum Email_PriorityCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nizkij = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Obychnyj = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Vysokij = 2,
	}
}