//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum Email_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CHernovik = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ne_vypolneno = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Otlozhennaya_otpravka = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Otmeneno = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Otpravka = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Otpravleno = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Polucheno = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Zaversheno = 2,
	}
}