//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum Email_EmailReminderType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Esli_soobschenie_elektronnoj_pochty_ne_budet_otkryto_do = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Esli_ya_ne_poluchu_otvet_do = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		V_lyubom_sluchae_napomnit_mne_v = 2,
	}
}