//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum Email_Notifications
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		net = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Soobschenie_bylo_sohraneno_v_vide_zapisi_elektronnoj_pochty_Microsoft_Dynamics_365_no_s_nim_byli_sohraneny_ne_vse_vlozheniya_Vlozhenie_ne_mozhet_byt_sohraneno_esli_ono_zablokirovano_ili_ego_tip_fajla_nedopustim = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tekst_usechen = 2,
	}
}