//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum Email_CorrelationMethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConversationIndex = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomCorrelation = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InReplyTo = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Propuscheno = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SmartMatching = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TrackingToken = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		XHeader = 2,
	}
}