//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum new_contract_plan_adjustment_cc_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Na_soglasovanii_v_KC = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Na_utverzhdenii = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Utverzhden = 899020000,
	}
}