//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum new_t_activity_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Aktivnaya_1608 = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ne_sostoyalas = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Novaya_1608 = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Podgotovka_dokumentacii_ne_ispolzuetsya = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Predvaritelnyj_presejl_ne_ispolzuetsya = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Presejl_ne_ispolzuetsya = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sostoyalas = 2,
	}
}