//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum new_negotiationoptionslist
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ne_soglasovano = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Soglasovano = 100000001,
	}
}