//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum new_contract_plan_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CHernovik = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Na_soglasovanii_v_KC = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Na_soglasovanii_v_MRF = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Na_utverzhdenii = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Utverzhden = 100000004,
	}
}