//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum new_quarter
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1_kvartal = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2_kvartal = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_3_kvartal = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_4_kvartal = 100000003,
	}
}