//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum new_contract_plan_product_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CHernovik = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Na_soglasovanii = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Soglasovan = 100000000,
	}
}