//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum Workflow_BusinessProcessType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Biznes_process = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Potok_zadach = 1,
	}
}