//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdsoft.RTK.CRMData.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum Workflow_Scope
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Podrazdelenie = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Polzovatel = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Predpriyatie = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Roditelskij_element__dochernie_podrazdeleniya = 3,
	}
}